
version: '3.1'

services:
  postgres:
    container_name: postgres_SDSDELIVER
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567
      
      
    ports:
      - "5433:5433"

    restart: unless-stopped